export const expandedSongLibrary = [
  // PERFECT MATCH TIER - Key F (15 songs)
  {
    title: "Way Maker",
    artist: "Leeland",
    key: "F",
    chords: ["F", "C", "Dm", "Bb"],
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/results?search_query=Way+Maker+Leeland+official",
    tier: "Perfect",
    ministry: "General",
    duration: "3:32",
    popularity: "High",
  },
  {
    title: "Build My Life",
    artist: "Pat Barrett",
    key: "F",
    chords: ["F", "C", "Dm", "Bb"],
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/results?search_query=Build+My+Life+Pat+Barrett+worship",
    tier: "Perfect",
    ministry: "General",
    duration: "4:28",
    popularity: "High",
  },
  {
    title: "10,000 Reasons (Bless the Lord)",
    artist: "Matt Redman",
    key: "F",
    chords: ["F", "C", "Dm", "Bb"],
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=DXDGE_lRI0E",
    tier: "Perfect",
    ministry: "General",
    duration: "4:32",
    popularity: "Very High",
  },
  {
    title: "I Speak Jesus",
    artist: "Charity Gayle",
    key: "F",
    chords: ["F", "Am", "Bb", "C"],
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/results?search_query=I+Speak+Jesus+Charity+Gayle",
    tier: "Perfect",
    ministry: "Lifestyle Christianity",
    duration: "4:12",
    popularity: "High",
  },
  {
    title: "Great Are You Lord",
    artist: "All Sons & Daughters",
    key: "F",
    chords: ["F", "Bb", "C", "Dm"],
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/results?search_query=Great+Are+You+Lord+All+Sons+Daughters",
    tier: "Perfect",
    ministry: "General",
    duration: "4:41",
    popularity: "Medium",
  },
  {
    title: "Cornerstone",
    artist: "Hillsong",
    key: "F",
    chords: ["F", "C", "Dm", "Bb"],
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/results?search_query=Cornerstone+Hillsong+worship",
    tier: "Perfect",
    ministry: "General",
    duration: "6:21",
    popularity: "High",
  },
  {
    title: "Do It Again",
    artist: "Elevation Worship",
    key: "F",
    chords: ["F", "C", "Dm", "Bb"],
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/results?search_query=Do+It+Again+Elevation+Worship",
    tier: "Perfect",
    ministry: "General",
    duration: "4:52",
    popularity: "High",
  },
  {
    title: "Champion",
    artist: "Dante Bowe",
    key: "F",
    chords: ["F", "C", "Dm", "Bb"],
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/results?search_query=Champion+Dante+Bowe+Maverick",
    tier: "Perfect",
    ministry: "Lifestyle Christianity",
    duration: "4:28",
    popularity: "Medium",
  },
  {
    title: "In Christ Alone",
    artist: "Kristian Stanfill",
    key: "F",
    chords: ["F", "C", "Dm", "Bb"],
    platform: "PraiseCharts",
    videoUrl: "https://www.youtube.com/results?search_query=In+Christ+Alone+Kristian+Stanfill",
    tier: "Perfect",
    ministry: "General",
    duration: "5:15",
    popularity: "High",
  },
  {
    title: "God Is Good",
    artist: "Phil Wickham",
    key: "F",
    chords: ["F", "C", "Dm", "Bb"],
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/results?search_query=God+Is+Good+Phil+Wickham",
    tier: "Perfect",
    ministry: "General",
    duration: "4:05",
    popularity: "Medium",
  },
  {
    title: "Firm Foundation",
    artist: "Maverick City Music",
    key: "F",
    chords: ["F", "C", "Dm", "Bb"],
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/results?search_query=Firm+Foundation+Maverick+City",
    tier: "Perfect",
    ministry: "General",
    duration: "6:31",
    popularity: "High",
  },
  {
    title: "Jireh",
    artist: "Elevation Worship & Maverick City",
    key: "F",
    chords: ["F", "C", "Dm", "Bb"],
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/results?search_query=Jireh+Elevation+Maverick+City",
    tier: "Perfect",
    ministry: "General",
    duration: "4:44",
    popularity: "Very High",
  },
  {
    title: "Always On Time",
    artist: "Elevation Worship",
    key: "F",
    chords: ["F", "C", "Dm", "Bb"],
    platform: "PraiseCharts",
    videoUrl: "https://www.youtube.com/results?search_query=Always+On+Time+Elevation+Worship",
    tier: "Perfect",
    ministry: "General",
    duration: "4:18",
    popularity: "Medium",
  },
  {
    title: "Give Thanks",
    artist: "Don Moen",
    key: "F",
    chords: ["F", "C", "Dm", "Bb"],
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/results?search_query=Give+Thanks+Don+Moen",
    tier: "Perfect",
    ministry: "General",
    duration: "4:21",
    popularity: "High",
  },
  {
    title: "Above All",
    artist: "Michael W. Smith",
    key: "F",
    chords: ["F", "C", "Dm", "Bb"],
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/results?search_query=Above+All+Michael+W+Smith",
    tier: "Perfect",
    ministry: "General",
    duration: "4:07",
    popularity: "High",
  },

  // PERFECT MATCH TIER - Key Dm (12 songs)
  {
    title: "Goodness of God",
    artist: "Bethel Music",
    key: "Dm",
    chords: ["Dm", "Bb", "F", "C"],
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/results?search_query=Goodness+of+God+Bethel+Music+Jenn+Johnson",
    tier: "Perfect",
    ministry: "General",
    duration: "5:18",
    popularity: "Very High",
  },
  {
    title: "Oceans (Where Feet May Fail)",
    artist: "Hillsong UNITED",
    key: "Dm",
    chords: ["Dm", "Bb", "F", "C"],
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=dy9nwe9_xzw",
    tier: "Perfect",
    ministry: "General",
    duration: "8:45",
    popularity: "Very High",
  },
  {
    title: "What a Beautiful Name",
    artist: "Hillsong Worship",
    key: "Dm",
    chords: ["Dm", "Bb", "F", "C"],
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/results?search_query=What+a+Beautiful+Name+Hillsong+Worship",
    tier: "Perfect",
    ministry: "General",
    duration: "4:18",
    popularity: "Very High",
  },
  {
    title: "Reckless Love",
    artist: "Cory Asbury",
    key: "Dm",
    chords: ["Dm", "Bb", "F", "C"],
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/results?search_query=Reckless+Love+Cory+Asbury+Bethel",
    tier: "Perfect",
    ministry: "General",
    duration: "5:18",
    popularity: "Very High",
  },
  {
    title: "No Longer Slaves",
    artist: "Bethel Music",
    key: "Dm",
    chords: ["Dm", "Bb", "F", "C"],
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/results?search_query=No+Longer+Slaves+Bethel+Music",
    tier: "Perfect",
    ministry: "General",
    duration: "5:32",
    popularity: "High",
  },
  {
    title: "King of My Heart",
    artist: "Bethel Music",
    key: "Dm",
    chords: ["Dm", "Bb", "F", "C"],
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/results?search_query=King+of+My+Heart+Bethel+Music",
    tier: "Perfect",
    ministry: "General",
    duration: "4:44",
    popularity: "High",
  },
  {
    title: "Tremble",
    artist: "Mosaic MSC",
    key: "Dm",
    chords: ["Dm", "Bb", "F", "C"],
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/results?search_query=Tremble+Mosaic+MSC+worship",
    tier: "Perfect",
    ministry: "Lifestyle Christianity",
    duration: "6:23",
    popularity: "Medium",
  },
  {
    title: "Graves Into Gardens",
    artist: "Elevation Worship",
    key: "Dm",
    chords: ["Dm", "Bb", "F", "C"],
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/results?search_query=Graves+Into+Gardens+Elevation+Worship",
    tier: "Perfect",
    ministry: "General",
    duration: "5:17",
    popularity: "High",
  },
  {
    title: "Holy Spirit",
    artist: "Kari Jobe",
    key: "Dm",
    chords: ["Dm", "Bb", "F", "C"],
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/results?search_query=Holy+Spirit+Kari+Jobe",
    tier: "Perfect",
    ministry: "General",
    duration: "5:43",
    popularity: "High",
  },
  {
    title: "The Blessing",
    artist: "Elevation Worship",
    key: "Dm",
    chords: ["Dm", "Bb", "F", "C"],
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/results?search_query=The+Blessing+Elevation+Worship",
    tier: "Perfect",
    ministry: "General",
    duration: "6:07",
    popularity: "Very High",
  },
  {
    title: "Promises",
    artist: "Maverick City Music",
    key: "Dm",
    chords: ["Dm", "Bb", "F", "C"],
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/results?search_query=Promises+Maverick+City+Music",
    tier: "Perfect",
    ministry: "General",
    duration: "4:04",
    popularity: "High",
  },
  {
    title: "Gratitude",
    artist: "Brandon Lake",
    key: "Dm",
    chords: ["Dm", "Bb", "F", "C"],
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/results?search_query=Gratitude+Brandon+Lake",
    tier: "Perfect",
    ministry: "General",
    duration: "4:32",
    popularity: "High",
  },

  // STRONG MATCH TIER - Key C (8 songs)
  {
    title: "How Great Is Our God",
    artist: "Chris Tomlin",
    key: "C",
    chords: ["C", "Am", "F", "G"],
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/results?search_query=How+Great+Is+Our+God+Chris+Tomlin",
    tier: "Strong",
    ministry: "General",
    duration: "4:38",
    popularity: "Very High",
  },
  {
    title: "Amazing Grace (My Chains Are Gone)",
    artist: "Chris Tomlin",
    key: "C",
    chords: ["C", "Am", "F", "G"],
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/results?search_query=Amazing+Grace+My+Chains+Are+Gone+Chris+Tomlin",
    tier: "Strong",
    ministry: "General",
    duration: "4:35",
    popularity: "Very High",
  },
  {
    title: "Good Good Father",
    artist: "Chris Tomlin",
    key: "C",
    chords: ["C", "Am", "F", "G"],
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/results?search_query=Good+Good+Father+Chris+Tomlin",
    tier: "Strong",
    ministry: "General",
    duration: "4:54",
    popularity: "High",
  },
  {
    title: "Holy Forever",
    artist: "Chris Tomlin",
    key: "C",
    chords: ["C", "Am", "F", "G"],
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=ZQ6IB1LrEAE",
    tier: "Strong",
    ministry: "General",
    duration: "5:13",
    popularity: "Very High",
  },
  {
    title: "Holy Spirit",
    artist: "Francesca Battistelli",
    key: "C",
    chords: ["C", "Am", "F", "G"],
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/results?search_query=Holy+Spirit+Francesca+Battistelli",
    tier: "Strong",
    ministry: "General",
    duration: "3:58",
    popularity: "Medium",
  },
  {
    title: "How Great Thou Art",
    artist: "Various Artists",
    key: "C",
    chords: ["C", "Am", "F", "G"],
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/results?search_query=How+Great+Thou+Art+worship",
    tier: "Strong",
    ministry: "General",
    duration: "4:42",
    popularity: "Very High",
  },
  {
    title: "Shout to the Lord",
    artist: "Hillsong",
    key: "C",
    chords: ["C", "Am", "F", "G"],
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/results?search_query=Shout+to+the+Lord+Hillsong",
    tier: "Strong",
    ministry: "General",
    duration: "4:41",
    popularity: "High",
  },
  {
    title: "Our Father",
    artist: "Bethel Music",
    key: "C",
    chords: ["C", "Am", "F", "G"],
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/results?search_query=Our+Father+Bethel+Music",
    tier: "Strong",
    ministry: "General",
    duration: "4:35",
    popularity: "Medium",
  },

  // CREATIVE MATCH TIER - Key Bb (5 songs)
  {
    title: "Blessed Be Your Name",
    artist: "Matt Redman",
    key: "Bb",
    chords: ["Bb", "F", "Gm", "Eb"],
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/results?search_query=Blessed+Be+Your+Name+Matt+Redman",
    tier: "Creative",
    ministry: "General",
    duration: "4:23",
    popularity: "High",
  },
  {
    title: "How Deep the Father's Love",
    artist: "Stuart Townend",
    key: "Bb",
    chords: ["Bb", "Gm", "Eb", "F"],
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/results?search_query=How+Deep+the+Father%27s+Love+Stuart+Townend",
    tier: "Creative",
    ministry: "General",
    duration: "5:12",
    popularity: "Medium",
  },
  {
    title: "God Will Make a Way",
    artist: "Don Moen",
    key: "Bb",
    chords: ["Bb", "F", "Gm", "Eb"],
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/results?search_query=God+Will+Make+a+Way+Don+Moen",
    tier: "Creative",
    ministry: "General",
    duration: "4:13",
    popularity: "High",
  },
  {
    title: "Arise",
    artist: "William Murphy",
    key: "Bb",
    chords: ["Bb", "F", "Gm", "Eb"],
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/results?search_query=Arise+William+Murphy",
    tier: "Creative",
    ministry: "General",
    duration: "5:47",
    popularity: "Medium",
  },
  {
    title: "In Jesus Name",
    artist: "Katy Nichole",
    key: "Bb",
    chords: ["Bb", "F", "Gm", "Eb"],
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/results?search_query=In+Jesus+Name+Katy+Nichole",
    tier: "Creative",
    ministry: "General",
    duration: "3:21",
    popularity: "High",
  },
]

export type Song = (typeof expandedSongLibrary)[0]
